name: CI/CD Pipeline DevOps

# Pemicu: pipeline berjalan saat ada push ke branch 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Menjalankan tes dan analisis kode
  test_and_analyze:
    # Menjalankan semua job di runner lokal Anda
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Langkah SonarQube sekarang diaktifkan kembali
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # Job 2: Membangun dan mendorong image Docker
  build_and_push:
    needs: test_and_analyze
    # Menjalankan semua job di runner lokal Anda
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest # Ganti dengan nama image Anda

  # Job 3: Deploy ke Kubernetes
  deploy:
    needs: build_and_push
    # Menjalankan semua job di runner lokal Anda
    runs-on: self-hosted
    steps:
      - name: Deploy to Minikube
        run: |
          echo "Deploying to Minikube..."
          kubectl set image deployment/login-app-deployment web-app=${{ secrets.DOCKERHUB_USERNAME }}/uas-devops-app:latest
